export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'; 

export const REQUEST_DEVELOPERS_PENDING = 'REQUEST_DEVELOPERS_PENDING';
export const REQUEST_DEVELOPERS_SUCCESS = 'REQUEST_DEVELOPERS_SUCCESS';
export const REQUEST_DEVELOPERS_FAILED = 'REQUEST_DEVELOPERS_FAILED';